# Generated by Django 3.1.4 on 2020-12-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OneToOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtercode', models.CharField(max_length=30, unique=True)),
                ('filtername', models.CharField(max_length=30)),
                ('filterdetail', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagecode', models.CharField(max_length=30, unique=True)),
                ('isbytime', models.BooleanField(default=True)),
                ('isbyusage', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('exfiltermonth', models.IntegerField(default=6)),
                ('exfiltervolume', models.IntegerField(default=2500)),
                ('packagedetail', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffcode', models.CharField(max_length=30, unique=True)),
                ('staffshort', models.CharField(default='', max_length=5)),
                ('staffname', models.CharField(max_length=30)),
                ('staffcontact', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=100, unique=True)),
                ('installaddress1', models.TextField(max_length=100)),
                ('installaddress2', models.TextField(blank=True, max_length=300)),
                ('photoncode', models.CharField(max_length=100)),
                ('mac', models.CharField(blank=True, max_length=100, unique=True)),
                ('installdate', models.DateField(auto_now_add=True, null=True)),
                ('nextservicedate', models.DateField(blank=True, null=True)),
                ('producttype', models.CharField(choices=[('WPU', 'Water Purifier'), ('U', 'Under Sink'), ('F', 'Filter')], max_length=3)),
                ('price', models.FloatField()),
                ('main_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mainpack')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OneToOne.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('casetype', models.CharField(choices=[('Filter replacement', 'Filter replacement'), ('Urgent Repair', 'Urgent Repair'), ('Installation', 'Installation'), ('Checking', 'Checking')], max_length=100)),
                ('scheduledate', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('action', models.TextField(blank=True, max_length=100)),
                ('suggest', models.TextField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=100)),
                ('iscompleted', models.BooleanField(blank=True, default=False)),
                ('filters', models.ManyToManyField(blank=True, to='management.Filter')),
                ('handledby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.technician')),
                ('machines', models.ManyToManyField(to='management.Machine')),
            ],
        ),
    ]
