# Generated by Django 3.1.4 on 2021-06-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0003_auto_20210317_1729'),
        ('management', '0002_auto_20210317_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetype', models.CharField(choices=[('Filter replacement', 'Filter replacement'), ('Urgent Repair', 'Urgent Repair'), ('Installation', 'Installation'), ('Checking', 'Checking')], max_length=100)),
                ('doctype', models.CharField(choices=[('Job Sheet', 'Job Sheet'), ('Renewal Letter', 'Renewal Letter'), ('Table', 'Table'), ('Others', 'Others')], max_length=100)),
                ('date', models.DateField(null=True)),
                ('scandate', models.DateField(null=True)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('image_path', models.CharField(max_length=200, unique=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OneToOne.customer')),
            ],
        ),
    ]
