# Generated by Django 3.1.4 on 2021-02-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201210_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='installdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mainpack'),
        ),
    ]
