# Generated by Django 3.1.4 on 2021-06-29 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('code_of_verification', models.CharField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('companyname', models.CharField(blank=True, max_length=200)),
                ('billingaddress', models.TextField(max_length=100)),
                ('installaddress', models.TextField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('invitationcode', models.CharField(max_length=20)),
                ('joindate', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Online', 'Online'), ('Referral', ' Referral'), ('Old', 'Old Customer'), ('Phone', ' Phone Call')], max_length=20)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('isconfirm', models.BooleanField(default=False)),
                ('customercode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
