# Generated by Django 3.1.4 on 2021-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('companyname', models.CharField(blank=True, max_length=200)),
                ('billingaddress', models.TextField(max_length=100)),
                ('installaddress', models.TextField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('invitationcode', models.CharField(max_length=20)),
                ('joindate', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Online', 'Online'), ('Referral', ' Referral'), ('Old', 'Old Customer'), ('Phone', ' Phone Call')], max_length=20)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('isconfirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
